name: CheckPython

on: [push, pull_request]

jobs:
  clean-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"